name: mapie-doc
channels:
    - defaults
    - conda-forge
dependencies:
    - numpydoc=1.1.0
    - pandas=1.3.5
    - python=3.8
    - scikit-learn=1.0.1
    - sphinx=4.3.2
    - sphinx-gallery=0.10.1
    - sphinx_rtd_theme=1.0.0
    - typing_extensions=4.0.1
